### ISSUE TITLE
Add in point mapping priority array

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#377]
Make its so the priority array will work over point mapping

Lets get it working between generic and modbus as a starting point

**Comment by RaiBnod** [comment]
When we sync value between modbus <> generic points. We are syncing the values, not the priority array. Value for modbus is:
- For reading operation: we read from modbus and directly edit the value (we don't care priority array on reading)
- For writing operation: we read values from the priority array and we write the highest value from the write priority array to a real device and when the writing got to succeed, we update the value.

The current must be on when we have values on generic points as this:

```JSON
{
  "_15": 11,
  "_16": 10
}
```

And when our Modbus value got changed into something else let's say 13, it changes generic values into this:

```JSON
{
  "_15": 11,
  "_16": 13
}
```

Resulting, no effect on the Generic Point value. So, we need to sync the whole priority_array instead of just value.
